### ISSUE TITLE
fix issue with event looper

### ISSUE THREAD

**Issue by ziyadm** [ziyadm/test-bot-repo#142]
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<EventHandler.__enforce_time_limits_loop() done, defined at /Users/ziyadm/Desktop/code/test-bot-repo/event_handler.py:13> exception=KeyError('discord_channel_id')>
Traceback (most recent call last):
  File "/Users/ziyadm/Desktop/code/test-bot-repo/event_handler.py", line 15, in __enforce_time_limits_loop
    _ = await self.__state.enforce_time_limits()
  File "/Users/ziyadm/Desktop/code/test-bot-repo/state.py", line 177, in enforce_time_limits
    all_missions = await Mission.rows(formula=None, airtable_client=self.airtable_client)
  File "/Users/ziyadm/Desktop/code/test-bot-repo/mission.py", line 146, in rows
    return [cls.__of_airtable_response(response) for response in responses]
  File "/Users/ziyadm/Desktop/code/test-bot-repo/mission.py", line 146, in <listcomp>
    return [cls.__of_airtable_response(response) for response in responses]
  File "/Users/ziyadm/Desktop/code/test-bot-repo/mission.py", line 129, in __of_airtable_response
    return cls(record_id=response.record_id, fields=Fields.of_dict(response.fields))
  File "/Users/ziyadm/Desktop/code/test-bot-repo/mission.py", line 88, in of_dict
    discord_channel_id=fields[cls.discord_channel_id_field],
KeyError: 'discord_channel_id'

**Comment by ziyadm** [comment]
this happens when airtable has empty rows in the missions table - shouldn't be a problem
